# === App Config ===
spring.application.name=chat-service
spring.config.import=optional:file:.env[.properties],optional:file:./UPLEARN/.env[.properties]

server.port=8091
spring.jackson.time-zone=America/Bogota

# === Mongo ===
spring.data.mongodb.uri=${DB_URI}
spring.data.mongodb.database=${DB_NAME}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.auto-index-creation=true

# === CORS ===
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:8080

# === Redis ===
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}

# === External services ===
users.api.base=${USERS_BASE:http://localhost:8080/Api-user}
users.public.path=${USERS_PUBLIC_PATH:/public/profile}
reservations.api.base=${RESERVATIONS_BASE:http://localhost:8090/api/reservations}

# === Cache ===
roles.cache.ttl-seconds=${ROLES_CACHE_TTL:240}
roles.cache.max-size=${ROLES_CACHE_MAX:10000}
profiles.cache.ttl-seconds=${PROFILES_CACHE_TTL:${ROLES_CACHE_TTL:240}}
profiles.cache.max-size=${PROFILES_CACHE_MAX:${ROLES_CACHE_MAX:10000}}

logging.level.co.edu.escuelaing.uplearn.chat=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always
